"""
AD Speed Profile Viewer — Flask Web App (v2)
=============================================
Serves interactive per-gene RNAPII instantaneous speed profiles generated by
07_ad_speed_profiles.py, plus research dashboard with strategy log, todos,
epigenomics, temporal rephasing, and pipeline status.

Three speed estimation approaches are visualized side by side:
  A: v(p) = C / rho_40m(p)         — raw 40m coverage
  B: v(p) = C / (rho_40m - rho_0m) — differential coverage
  C: multi-timepoint product group  — Z_M × Z_3 average

New endpoints in v2:
  GET /api/strategy   — parsed STRATEGY_LOG.md sessions + current results
  GET /api/todos      — active/completed TODO items from STRATEGY_LOG.md
  GET /api/status     — pipeline status (which data exists)
  GET /api/epigenomics/<gene_file> — per-gene epigenomic marks (if available)
  GET /api/temporal/<gene_file>    — temporal rephased profiles (if available)

Run:
  cd <project>/webapp
  python3 app.py

Then open: http://localhost:5050
"""

import json
import math
import os
import re
from pathlib import Path
from datetime import datetime

from flask import Flask, render_template, jsonify, send_from_directory

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE          = Path(__file__).parent.parent
PROFILES_DIR  = BASE / "results" / "speed_profiles"
RESULTS_DIR   = BASE / "results"
EPIGENOMICS_DIR = BASE / "results" / "epigenomics"
TEMPORAL_DIR  = BASE / "results" / "temporal_profiles"
PRESENTATION_DIR = BASE / "presentation"
STRATEGY_LOG  = BASE / "STRATEGY_LOG.md"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_load(path):
    """Load a JSON file, replacing NaN/Infinity with None (null) before parsing."""
    content = path.read_text()
    content = re.sub(r'\bNaN\b', 'null', content)
    content = re.sub(r'(?<!["\w])-?Infinity\b', 'null', content)
    return json.loads(content)


def _parse_strategy_log():
    """
    Parse STRATEGY_LOG.md into structured data.

    Returns a dict with:
      sessions: list of {number, date, title, summary}
      current_results: dict of method -> {pearson_r, spearman_rho}
      todos: {active: [...], completed: [...], total: int}
    """
    if not STRATEGY_LOG.exists():
        return None

    text = STRATEGY_LOG.read_text(encoding="utf-8")

    # --- Parse sessions -------------------------------------------------------
    # Sessions are delimited by lines like "## Session N — YYYY-MM-DD ..."
    session_pattern = re.compile(
        r'^##\s+Session\s+(\d+)\s*[—\-–]\s*(\d{4}-\d{2}-\d{2})(.*?)$',
        re.MULTILINE
    )
    sessions = []
    session_matches = list(session_pattern.finditer(text))

    for i, m in enumerate(session_matches):
        number = int(m.group(1))
        date   = m.group(2)
        suffix = m.group(3).strip().lstrip('(').rstrip(')')

        # Extract the body of this session (up to the next session heading)
        body_start = m.end()
        body_end   = session_matches[i + 1].start() if i + 1 < len(session_matches) else len(text)
        body       = text[body_start:body_end]

        # First non-empty ### sub-heading is the objective/title
        subhead = re.search(r'^###\s+(.+)$', body, re.MULTILINE)
        title   = subhead.group(1).strip() if subhead else (suffix or f"Session {number}")

        # Build a short summary from the first paragraph-ish block of text
        # (skip sub-headings, bullet lists; grab first prose paragraph)
        paras = []
        for line in body.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith('#') or stripped.startswith('|'):
                if paras:
                    break
                continue
            if stripped.startswith('-') or stripped.startswith('*'):
                continue
            paras.append(stripped)
            if len(' '.join(paras)) > 200:
                break

        summary = ' '.join(paras)[:300]
        if not summary:
            summary = f"Session covering {title}."

        sessions.append({
            "number":  number,
            "date":    date,
            "title":   title,
            "summary": summary,
        })

    # --- Parse current results -----------------------------------------------
    # Look for the results table / key Pearson/Spearman numbers
    current_results = {}

    # groHMM result
    grohmm_pearson = re.search(r'groHMM.*?Pearson\s+r\s*[=:]\s*([\d.]+)', text, re.IGNORECASE | re.DOTALL)
    grohmm_spear   = re.search(r'groHMM.*?Spearman\s+[ρp]\s*[=:]\s*([\d.]+)', text, re.IGNORECASE | re.DOTALL)
    # Also try the explicit table format in Session 3
    grohmm_table   = re.search(r'groHMM Python\s+([\d.]+)\s+([\d.]+)', text)
    psi_table      = re.search(r'AD\s+[ψp]\s+\(diff40\)\s+([\d.]+)\s+([\d.]+)', text)

    if grohmm_table:
        current_results["groHMM"] = {
            "pearson_r":    float(grohmm_table.group(1)),
            "spearman_rho": float(grohmm_table.group(2)),
            "label": "groHMM (wave-front HMM)",
        }
    elif grohmm_pearson and grohmm_spear:
        current_results["groHMM"] = {
            "pearson_r":    float(grohmm_pearson.group(1)),
            "spearman_rho": float(grohmm_spear.group(1)),
            "label": "groHMM (wave-front HMM)",
        }

    if psi_table:
        current_results["psi_ad"] = {
            "pearson_r":    float(psi_table.group(1)),
            "spearman_rho": float(psi_table.group(2)),
            "label": "AD spectral concentration ψ",
        }

    # Method A / B results — look for explicit statements
    mA = re.search(r'Method\s+A.*?Pearson\s+r\s*[=:]\s*([\d.]+).*?Spearman\s+[ρp]\s*[=:]\s*([\d.]+)', text, re.IGNORECASE | re.DOTALL)
    mB = re.search(r'Method\s+B.*?Pearson\s+r\s*[=:]\s*([\d.]+).*?Spearman\s+[ρp]\s*[=:]\s*([\d.]+)', text, re.IGNORECASE | re.DOTALL)

    if mA:
        current_results["method_A"] = {
            "pearson_r":    float(mA.group(1)),
            "spearman_rho": float(mA.group(2)),
            "label": "Method A: C/ρ₄₀ₘ",
        }
    if mB:
        current_results["method_B"] = {
            "pearson_r":    float(mB.group(1)),
            "spearman_rho": float(mB.group(2)),
            "label": "Method B: C/(ρ₄₀ₘ−ρ₀ₘ)",
        }

    # Fallback: embed known results from Session 3 if regex didn't catch them
    if not current_results:
        current_results = {
            "groHMM":   {"pearson_r": 0.514, "spearman_rho": 0.601, "label": "groHMM (wave-front HMM)"},
            "method_A": {"pearson_r": 0.288, "spearman_rho": 0.603, "label": "Method A: C/ρ₄₀ₘ"},
            "method_B": {"pearson_r": 0.288, "spearman_rho": 0.602, "label": "Method B: C/(ρ₄₀ₘ−ρ₀ₘ)"},
            "psi_ad":   {"pearson_r": 0.557, "spearman_rho": 0.468, "label": "AD spectral concentration ψ"},
        }

    # --- Parse TODO items ----------------------------------------------------
    # Match Markdown task list items:  - [ ] text  or  - [x] text
    todo_pattern = re.compile(r'^\s*-\s+\[( |x|X)\]\s+(.+)$', re.MULTILINE)
    active    = []
    completed = []
    for m in todo_pattern.finditer(text):
        checked = m.group(1).strip().lower()
        item    = m.group(2).strip()
        if checked == 'x':
            completed.append(item)
        else:
            active.append(item)

    todos = {
        "active":    active,
        "completed": completed,
        "total":     len(active) + len(completed),
    }

    return {
        "sessions":        sessions,
        "current_results": current_results,
        "todos":           todos,
    }


def _pipeline_status():
    """
    Check which data types exist and return a status dict.
    """
    idx_path   = PROFILES_DIR / "_gene_index.json"
    n_genes    = 0
    gene_profiles = idx_path.exists()

    if gene_profiles:
        try:
            genes = _safe_load(idx_path)
            n_genes = len(genes)
        except Exception:
            pass

    epigenomics = EPIGENOMICS_DIR.exists() and any(EPIGENOMICS_DIR.iterdir()) if EPIGENOMICS_DIR.exists() else False
    temporal    = TEMPORAL_DIR.exists() and any(TEMPORAL_DIR.iterdir()) if TEMPORAL_DIR.exists() else False

    # Check for RNA folding data in results
    folding_candidates = [
        BASE / "results" / "folding",
        BASE / "results" / "rna_folding",
        BASE / "data" / "folding",
    ]
    folding = any(p.exists() for p in folding_candidates)

    # Check which key result files exist
    result_files = {
        "grohmm_rates":       (RESULTS_DIR / "grohmm_wave_rates.csv").exists(),
        "speed_profiles":     (RESULTS_DIR / "ad_speed_rates.csv").exists(),
        "psi_correlation":    (RESULTS_DIR / "psi_vs_danko_rates.csv").exists(),
        "benchmark_csv":      (RESULTS_DIR / "benchmark_correlation.png").exists(),
        "grohmm_figure":      (RESULTS_DIR / "grohmm_vs_danko_comparison.png").exists(),
        "final_comparison":   (RESULTS_DIR / "final_comparison.png").exists(),
    }

    return {
        "gene_profiles":            gene_profiles,
        "epigenomics_downloaded":   epigenomics,
        "temporal_profiles":        temporal,
        "folding_data":             folding,
        "n_genes":                  n_genes,
        "result_files":             result_files,
        "strategy_log_exists":      STRATEGY_LOG.exists(),
        "as_of":                    datetime.utcnow().isoformat() + "Z",
    }


# ---------------------------------------------------------------------------
# Existing API routes
# ---------------------------------------------------------------------------

@app.route("/api/genes")
def api_genes():
    """Return gene index with metadata."""
    idx_path = PROFILES_DIR / "_gene_index.json"
    if not idx_path.exists():
        return jsonify({"error": "Gene index not found. Run 07_ad_speed_profiles.py first."}), 404
    genes = _safe_load(idx_path)
    return jsonify(genes)


@app.route("/api/gene/<path:gene_file>")
def api_gene(gene_file):
    """Return full profile data for a single gene."""
    path = PROFILES_DIR / gene_file
    if not path.exists():
        return jsonify({"error": f"Profile not found: {gene_file}"}), 404
    data = _safe_load(path)
    return jsonify(data)


@app.route("/api/correlations")
def api_correlations():
    """Return cross-method correlation summary."""
    path = PROFILES_DIR / "_correlations.json"
    if not path.exists():
        return jsonify({"error": "Correlations not found."}), 404
    data = _safe_load(path)
    return jsonify(data)


@app.route("/api/figure/<fname>")
def api_figure(fname):
    """Serve result figures."""
    return send_from_directory(str(RESULTS_DIR), fname)


@app.route("/presentation/<path:fname>")
def presentation(fname):
    """
    Serve PDF presentations and speaker notes from presentation/.
    Forces Content-Disposition: attachment so the browser downloads the file.
    Whitelists *.pdf only.
    """
    if not fname.lower().endswith(".pdf"):
        return jsonify({"error": "Only .pdf downloads are allowed here."}), 400
    return send_from_directory(
        str(PRESENTATION_DIR),
        fname,
        as_attachment=True,
        mimetype="application/pdf",
    )


@app.route("/api/presentation")
def api_presentation():
    """
    List PDFs available in presentation/ with size and mtime so the UI can
    offer fresh download links.
    """
    if not PRESENTATION_DIR.exists():
        return jsonify({"files": []})
    files = []
    for p in sorted(PRESENTATION_DIR.glob("*.pdf")):
        stat = p.stat()
        files.append({
            "name":       p.name,
            "url":        f"/presentation/{p.name}",
            "size_bytes": stat.st_size,
            "size_mb":    round(stat.st_size / (1024 * 1024), 2),
            "mtime":      datetime.utcfromtimestamp(stat.st_mtime).isoformat() + "Z",
        })
    return jsonify({"files": files})


# ---------------------------------------------------------------------------
# New API routes (v2)
# ---------------------------------------------------------------------------

@app.route("/api/strategy")
def api_strategy():
    """
    Parse STRATEGY_LOG.md and return structured JSON with sessions and results.
    """
    parsed = _parse_strategy_log()
    if parsed is None:
        return jsonify({"error": "STRATEGY_LOG.md not found."}), 404

    return jsonify({
        "sessions":        parsed["sessions"],
        "current_results": parsed["current_results"],
    })


@app.route("/api/todos")
def api_todos():
    """
    Parse STRATEGY_LOG.md for Markdown task list items and return them.
    Active items: - [ ] text
    Completed items: - [x] text
    """
    parsed = _parse_strategy_log()
    if parsed is None:
        return jsonify({"error": "STRATEGY_LOG.md not found."}), 404

    return jsonify(parsed["todos"])


@app.route("/api/status")
def api_status():
    """
    Return pipeline status: which data types have been generated.
    """
    return jsonify(_pipeline_status())


@app.route("/api/epigenomics/<path:gene_file>")
def api_epigenomics(gene_file):
    """
    Return per-gene epigenomic mark data from results/epigenomics/.
    Returns 404 with a helpful message if epigenomics have not been downloaded.
    """
    if not EPIGENOMICS_DIR.exists():
        return jsonify({
            "error": "Epigenomics directory not found.",
            "hint":  "Run scripts/10_download_epigenomics.py to fetch ENCODE marks.",
            "marks": ["methylation", "H3K36me3", "H3K27ac", "H3K4me3", "H3K27me3", "CTCF"],
        }), 404

    path = EPIGENOMICS_DIR / gene_file
    if not path.exists():
        return jsonify({
            "error": f"Epigenomics profile not found: {gene_file}",
            "hint":  "Run scripts/10_download_epigenomics.py to generate profiles.",
        }), 404

    data = _safe_load(path)
    return jsonify(data)


@app.route("/api/temporal/<path:gene_file>")
def api_temporal(gene_file):
    """
    Return temporal rephased profile for a gene from results/temporal_profiles/.
    Returns 404 with a helpful message if temporal rephasing has not been run.
    """
    if not TEMPORAL_DIR.exists():
        return jsonify({
            "error": "Temporal profiles directory not found.",
            "hint":  "Run scripts/11_temporal_rephase.py to convert genomic → time coordinates.",
        }), 404

    path = TEMPORAL_DIR / gene_file
    if not path.exists():
        return jsonify({
            "error": f"Temporal profile not found: {gene_file}",
            "hint":  "Run scripts/11_temporal_rephase.py to generate this profile.",
        }), 404

    data = _safe_load(path)
    return jsonify(data)


# ---------------------------------------------------------------------------
# Main page
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5050))
    print(f"\n  AD Speed Profile Viewer v2")
    print(f"  Base dir:     {BASE}")
    print(f"  Profiles dir: {PROFILES_DIR}")
    print(f"  Strategy log: {STRATEGY_LOG} ({'found' if STRATEGY_LOG.exists() else 'MISSING'})")
    print(f"  Epigenomics:  {EPIGENOMICS_DIR} ({'found' if EPIGENOMICS_DIR.exists() else 'not yet'})")
    print(f"  Temporal:     {TEMPORAL_DIR} ({'found' if TEMPORAL_DIR.exists() else 'not yet'})")
    print(f"  Open: http://localhost:{port}\n")
    app.run(host="0.0.0.0", port=port, debug=False)
